/* Number shuffling.

   Each quiz has a scenario generator that picks a fresh, self-consistent set of
   numbers, and a recipe per question that rebuilds the wording, the answer and the
   working from that scenario. All plain arithmetic — nothing is fetched, nothing is
   generated by AI. Questions with no recipe simply keep their original numbers.

   A recipe is { text, answer, working, hint?, formula?, options?, tolerance? },
   each either a value or a function of the scenario. Anything it does not set
   (unit, suffix, tag, type) is inherited from the original question. */

/* ---------- helpers ---------- */

const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];

// step through a range, e.g. steps(10, 60, 5) -> [10, 15, ... 60]
function steps(min, max, step) {
  const out = [];
  for (let v = min; v <= max + 1e-9; v += step) out.push(Math.round(v * 1e6) / 1e6);
  return out;
}

const round = (v, dp = 2) => Math.round(v * 10 ** dp) / 10 ** dp;

// 1,20,000 / 3.3875 — trims trailing zeros, max 4 decimals
function num(v) {
  const r = Math.round(v * 10000) / 10000;
  const neg = r < 0;
  const [w, f] = String(Math.abs(r)).split(".");
  const grouped = w.length <= 3
    ? w
    : w.slice(0, -3).replace(/\B(?=(\d{2})+(?!\d))/g, ",") + "," + w.slice(-3);
  return (neg ? "-" : "") + grouped + (f ? `.${f}` : "");
}

const rs = (v) => `₹${num(v)}`; // rupees

/* ---------- quiz 1: Food Business Maths ---------- */

function businessScenario() {
  const teaPrice = pick([15, 20, 25, 30]);
  const teaCost = pick([5, 6, 7, 8]);
  const teaPriceB = pick([12, 15, 18, 20]);

  // sandwich: cost is a clean percentage of price, so Q14 stays a tidy number
  const sandPrice = pick([60, 80, 100, 120]);
  const sandPct = pick([25, 30, 35, 40]);
  const sandCost = (sandPrice * sandPct) / 100;
  const sandQty = pick(steps(30, 70, 10));

  // Q8/Q9: ingredient spend is a clean percentage of tea sales
  const q8Teas = pick([100, 150, 200]);
  const q8Pct = pick([30, 35, 40]);
  const q8Sales = q8Teas * teaPrice;
  const q8Ing = (q8Sales * q8Pct) / 100;

  // Q15: wastage is a clean percentage of stock
  const stock = pick([4000, 5000, 6000, 8000, 10000]);
  const wastePct = pick([4, 5, 6, 8, 10]);
  const wastage = (stock * wastePct) / 100;

  // Q19/21/22: fixed costs
  const rent = pick([24000, 30000, 36000, 45000]);   // all divide by 30
  const staff = pick([2, 3, 4]);
  const salary = pick([12000, 15000, 18000]);
  const utilities = pick([8000, 10000, 12000, 15000]);
  const fixedTotal = rent + staff * salary + utilities;
  const monthSales = pick([200000, 250000, 300000, 400000, 500000]);

  // Q25-27: one day's trading, used by all three.
  // Q24 compares the two margins, so they must not tie — keep the snack clearly ahead.
  let daySnackPrice, daySnackCost, dayTeaPrice, dayTeaCost;
  do {
    daySnackPrice = pick([80, 100, 120]);
    daySnackCost = pick([50, 60, 70]);
    dayTeaPrice = pick([20, 25, 30]);
    dayTeaCost = pick([7, 8, 10]);
  } while (daySnackPrice - daySnackCost < dayTeaPrice - dayTeaCost + 5);
  const dayTeaQty = pick(steps(40, 90, 10));
  const daySnackQty = pick(steps(20, 50, 10));
  const daySales = dayTeaQty * dayTeaPrice + daySnackQty * daySnackPrice;
  const dayIng = dayTeaQty * dayTeaCost + daySnackQty * daySnackCost;

  // Q28: target divides exactly by the average bill
  const avgBill = pick([80, 100, 120, 150, 200]);
  const bills = pick([50, 60, 80, 100, 120]);

  return {
    teaPrice, teaCost, teaPriceB,
    q1Cups: pick(steps(10, 60, 5)),
    q2Count: pick(steps(20, 60, 5)),
    q3Teas: pick([2, 3, 4]),
    snackPrice: pick([40, 50, 60, 70]),
    monday: pick(steps(3000, 6000, 100)),
    tuesday: pick(steps(3000, 6000, 100)),
    target: pick([8000, 10000, 12000, 15000]),
    sold: pick(steps(4000, 7500, 100)),
    q6Cups: pick(steps(50, 120, 10)),
    q8Teas, q8Sales, q8Ing, q8Pct,
    bought: pick([2000, 3000, 4000, 5000]),
    usedPct: pick([60, 70, 75, 80]),
    sandPrice, sandCost, sandPct, sandQty,
    stock, wastePct, wastage,
    opening: pick(steps(1500, 4000, 500)),
    purchases: pick(steps(6000, 12000, 1000)),
    closing: pick(steps(1000, 2500, 500)),
    made: pick(steps(30, 80, 10)),
    spilled: pick([2, 3, 4, 5]),
    portions: pick([80, 100, 120]),
    wasted: pick([4, 5, 6, 8]),
    portionPrice: pick([30, 40, 50, 60]),
    rent, staff, salary, utilities, fixedTotal, monthSales,
    lowPrice: pick([10, 12, 15]),
    dayTeaQty, daySnackQty, dayTeaPrice, dayTeaCost,
    daySnackPrice, daySnackCost, daySales, dayIng,
    avgBill, bills
  };
}

const BUSINESS_RECIPES = {
  1: {
    text: s => `You sell ${s.q1Cups} cups of tea at ₹${s.teaPrice} each. What are your total sales?`,
    answer: s => s.q1Cups * s.teaPrice,
    working: s => `${s.q1Cups} cups × ₹${s.teaPrice} = ${rs(s.q1Cups * s.teaPrice)}.`
  },
  2: {
    text: s => `You sell ${s.q2Count} sandwiches at ₹${s.sandPrice} each. What are your total sales?`,
    answer: s => s.q2Count * s.sandPrice,
    working: s => `${s.q2Count} × ₹${s.sandPrice} = ${rs(s.q2Count * s.sandPrice)}.`
  },
  3: {
    text: s => `A customer buys ${s.q3Teas} teas at ₹${s.teaPrice} each and 1 snack at ₹${s.snackPrice}. What is their bill?`,
    answer: s => s.q3Teas * s.teaPrice + s.snackPrice,
    working: s => `(${s.q3Teas} × ₹${s.teaPrice}) + ₹${s.snackPrice} = ${rs(s.q3Teas * s.teaPrice)} + ${rs(s.snackPrice)} = ${rs(s.q3Teas * s.teaPrice + s.snackPrice)}.`
  },
  4: {
    text: s => `You earn ${rs(s.monday)} on Monday and ${rs(s.tuesday)} on Tuesday. What are your sales across both days?`,
    answer: s => s.monday + s.tuesday,
    working: s => `${rs(s.monday)} + ${rs(s.tuesday)} = ${rs(s.monday + s.tuesday)}.`
  },
  5: {
    text: s => `Your target for the day is ${rs(s.target)}. You have sold ${rs(s.sold)}. How much more do you need to sell?`,
    answer: s => s.target - s.sold,
    working: s => `${rs(s.target)} − ${rs(s.sold)} = ${rs(s.target - s.sold)}.`
  },
  6: {
    text: s => `You sell ${s.q6Cups} cups of tea in a day. If each cup is ₹${s.teaPriceB}, what are daily tea sales?`,
    answer: s => s.q6Cups * s.teaPriceB,
    working: s => `${s.q6Cups} × ₹${s.teaPriceB} = ${rs(s.q6Cups * s.teaPriceB)}.`
  },
  7: {
    text: s => `One tea costs ₹${s.teaCost} in ingredients and sells for ₹${s.teaPrice}. How much money is left per tea before rent, salaries, and other expenses?`,
    answer: s => s.teaPrice - s.teaCost,
    working: s => `₹${s.teaPrice} − ₹${s.teaCost} = ${rs(s.teaPrice - s.teaCost)} left per tea.`
  },
  8: {
    text: s => `You sell ${s.q8Teas} teas at ₹${s.teaPrice} each. The ingredients for all ${s.q8Teas} teas cost ${rs(s.q8Ing)}. What are your total sales?`,
    answer: s => s.q8Sales,
    working: s => `${s.q8Teas} × ₹${s.teaPrice} = ${rs(s.q8Sales)}. The ${rs(s.q8Ing)} is a cost, not a sale.`
  },
  9: {
    text: s => `Using sales of ${rs(s.q8Sales)} and ingredient costs of ${rs(s.q8Ing)}, what percentage of sales was spent on ingredients?`,
    answer: s => s.q8Pct,
    working: s => `(${rs(s.q8Ing)} ÷ ${rs(s.q8Sales)}) × 100 = ${s.q8Pct}%.`
  },
  10: {
    text: s => `You buy ingredients worth ${rs(s.bought)} and use ${rs((s.bought * s.usedPct) / 100)} of them this week. How much ingredient stock remains?`,
    answer: s => s.bought - (s.bought * s.usedPct) / 100,
    working: s => `${rs(s.bought)} − ${rs((s.bought * s.usedPct) / 100)} = ${rs(s.bought - (s.bought * s.usedPct) / 100)} of stock left.`
  },
  11: {
    text: s => `A sandwich sells for ₹${s.sandPrice}. Its ingredients cost ₹${s.sandCost}. How much money is left from one sandwich before other expenses?`,
    answer: s => s.sandPrice - s.sandCost,
    working: s => `₹${s.sandPrice} − ₹${s.sandCost} = ${rs(s.sandPrice - s.sandCost)}.`
  },
  12: {
    text: s => `You sell ${s.sandQty} sandwiches. Each uses ingredients worth ₹${s.sandCost}. What is the total ingredient cost?`,
    answer: s => s.sandQty * s.sandCost,
    working: s => `${s.sandQty} × ₹${s.sandCost} = ${rs(s.sandQty * s.sandCost)}.`
  },
  13: {
    text: s => `You sell ${s.sandQty} sandwiches at ₹${s.sandPrice} each. What are total sales?`,
    answer: s => s.sandQty * s.sandPrice,
    working: s => `${s.sandQty} × ₹${s.sandPrice} = ${rs(s.sandQty * s.sandPrice)}.`
  },
  14: {
    text: s => `Ingredient cost is ${rs(s.sandQty * s.sandCost)} and sales are ${rs(s.sandQty * s.sandPrice)}. What is the food-cost percentage?`,
    answer: s => s.sandPct,
    working: s => `(${rs(s.sandQty * s.sandCost)} ÷ ${rs(s.sandQty * s.sandPrice)}) × 100 = ${s.sandPct}%.`
  },
  15: {
    text: s => `You bought ${rs(s.stock)} of stock. ${rs(s.wastage)} of it spoiled or was wasted. What percentage of the stock was wasted?`,
    answer: s => s.wastePct,
    working: s => `(${rs(s.wastage)} ÷ ${rs(s.stock)}) × 100 = ${s.wastePct}%.`
  },
  16: {
    text: s => `You begin the month with stock worth ${rs(s.opening)}. You purchase ${rs(s.purchases)} more. At the end of the month, stock worth ${rs(s.closing)} remains. What was the value of stock consumed?`,
    answer: s => s.opening + s.purchases - s.closing,
    working: s => `${rs(s.opening)} + ${rs(s.purchases)} − ${rs(s.closing)} = ${rs(s.opening + s.purchases - s.closing)} consumed.`
  },
  17: {
    text: s => `You make ${s.made} cups of tea, but ${s.spilled} are spilled or given away accidentally. How many cups can you still sell?`,
    answer: s => s.made - s.spilled,
    working: s => `${s.made} − ${s.spilled} = ${s.made - s.spilled} cups.`
  },
  18: {
    text: s => `You make ${s.portions} snack portions. ${s.wasted} are wasted. If each portion could have sold for ₹${s.portionPrice}, how much sales value was lost?`,
    answer: s => s.wasted * s.portionPrice,
    working: s => `${s.wasted} × ₹${s.portionPrice} = ${rs(s.wasted * s.portionPrice)} of sales value lost.`
  },
  19: {
    text: s => `Monthly rent is ${rs(s.rent)}. What is the rent per day in a 30-day month?`,
    answer: s => s.rent / 30,
    working: s => `${rs(s.rent)} ÷ 30 = ${rs(s.rent / 30)} per day.`
  },
  20: {
    text: s => `You have ${s.staff} staff members. Each earns ${rs(s.salary)} per month. What is the monthly salary cost?`,
    answer: s => s.staff * s.salary,
    working: s => `${s.staff} × ${rs(s.salary)} = ${rs(s.staff * s.salary)}.`
  },
  21: {
    text: s => `Rent is ${rs(s.rent)}, salaries are ${rs(s.staff * s.salary)}, and utilities are ${rs(s.utilities)} per month. What are total fixed costs?`,
    answer: s => s.fixedTotal,
    working: s => `${rs(s.rent)} + ${rs(s.staff * s.salary)} + ${rs(s.utilities)} = ${rs(s.fixedTotal)}.`
  },
  22: {
    text: s => `Your monthly sales are ${rs(s.monthSales)}. Your total fixed costs are ${rs(s.fixedTotal)}. What percentage of sales do fixed costs represent?`,
    answer: s => round((s.fixedTotal / s.monthSales) * 100, 2),
    tolerance: 0.2,
    working: s => `(${rs(s.fixedTotal)} ÷ ${rs(s.monthSales)}) × 100 = about ${num(round((s.fixedTotal / s.monthSales) * 100, 1))}%.`
  },
  23: {
    text: s => `A tea sells for ₹${s.lowPrice} but costs ₹${s.teaCost} to make. Why might this be an unsafe price in a high-rent location?`,
    options: s => [
      `It leaves only ${rs(s.lowPrice - s.teaCost)} before rent, salaries, and other expenses.`,
      "Tea cannot be sold in high-rent locations.",
      "The ingredient cost is higher than the selling price.",
      "High-rent locations do not need profit."
    ],
    answer: 0,
    working: s => `₹${s.lowPrice} − ₹${s.teaCost} = ${rs(s.lowPrice - s.teaCost)} per tea before rent, salaries and everything else. On a high rent, that may never add up to enough.`
  },
  24: {
    text: s => `A snack sells for ₹${s.daySnackPrice} and costs ₹${s.daySnackCost} to make. A tea sells for ₹${s.dayTeaPrice} and costs ₹${s.dayTeaCost} to make. Which item leaves more money per sale before other expenses?`,
    options: s => [
      `The snack, because it leaves ${rs(s.daySnackPrice - s.daySnackCost)}.`,
      `The tea, because it leaves ${rs(s.dayTeaPrice - s.dayTeaCost)}.`,
      "Both leave the same amount.",
      "There is not enough information."
    ],
    answer: s => (s.daySnackPrice - s.daySnackCost >= s.dayTeaPrice - s.dayTeaCost ? 0 : 1),
    working: s => `Snack: ₹${s.daySnackPrice} − ₹${s.daySnackCost} = ${rs(s.daySnackPrice - s.daySnackCost)}. Tea: ₹${s.dayTeaPrice} − ₹${s.dayTeaCost} = ${rs(s.dayTeaPrice - s.dayTeaCost)}. The ${s.daySnackPrice - s.daySnackCost >= s.dayTeaPrice - s.dayTeaCost ? "snack" : "tea"} leaves more per sale.`
  },
  25: {
    text: s => `You sell ${s.dayTeaQty} teas at ₹${s.dayTeaPrice} and ${s.daySnackQty} snacks at ₹${s.daySnackPrice}. What are your total sales for the day?`,
    answer: s => s.daySales,
    working: s => `(${s.dayTeaQty} × ₹${s.dayTeaPrice}) + (${s.daySnackQty} × ₹${s.daySnackPrice}) = ${rs(s.dayTeaQty * s.dayTeaPrice)} + ${rs(s.daySnackQty * s.daySnackPrice)} = ${rs(s.daySales)}.`
  },
  26: {
    text: s => `For the same day: tea ingredients cost ₹${s.dayTeaCost} each and snack ingredients cost ₹${s.daySnackCost} each. What is the total ingredient cost?`,
    answer: s => s.dayIng,
    working: s => `(${s.dayTeaQty} × ₹${s.dayTeaCost}) + (${s.daySnackQty} × ₹${s.daySnackCost}) = ${rs(s.dayTeaQty * s.dayTeaCost)} + ${rs(s.daySnackQty * s.daySnackCost)} = ${rs(s.dayIng)}.`
  },
  27: {
    text: s => `Sales are ${rs(s.daySales)} and ingredient costs are ${rs(s.dayIng)}. How much remains after ingredient costs, before rent, salaries, wastage, commissions, and other expenses?`,
    answer: s => s.daySales - s.dayIng,
    working: s => `${rs(s.daySales)} − ${rs(s.dayIng)} = ${rs(s.daySales - s.dayIng)}.`
  },
  28: {
    text: s => `You want ${rs(s.avgBill * s.bills)} in daily sales. If your average customer bill is ₹${s.avgBill}, how many customer bills do you need in one day?`,
    answer: s => s.bills,
    working: s => `${rs(s.avgBill * s.bills)} ÷ ₹${s.avgBill} = ${s.bills} customer bills.`
  }
};

/* ---------- quiz 2: Food Cost Maths ---------- */

function foodCostScenario() {
  const milkRate = pick([0.042, 0.048, 0.052, 0.06]);
  const milkMl = pick(steps(40, 60, 5));
  const waterRate = pick([0.00125, 0.00175, 0.002]);
  const waterMl = pick(steps(40, 60, 5));
  const teaRate = pick([0.25, 0.3, 0.35, 0.4]);
  const teaG = pick([2, 3, 4]);
  const gingerRate = pick([0.12, 0.15, 0.18, 0.2]);
  const gingerG = pick([2, 3, 4, 5]);
  const sugarRate = pick([0.03, 0.04, 0.05]);
  const sugarG = pick([5, 6, 8]);

  const milk = round(milkMl * milkRate, 4);
  const water = round(waterMl * waterRate, 4);
  const tea = round(teaG * teaRate, 4);
  const ginger = round(gingerG * gingerRate, 4);
  const sugar = round(sugarG * sugarRate, 4);

  // the chain that runs Q13 -> Q17, exactly as the original does
  const main = round(milk + water, 4);          // "main ingredients"
  const extras = round(ginger + sugar, 4);      // "extra ingredients"
  const total = round(main + extras, 4);
  const wastePct = pick([4, 5, 6]);
  const wasteAmt = round((total * wastePct) / 100, 2);
  const foodCost = round(total + wasteAmt, 4);

  const targetA = pick([25, 30, 33]);
  const targetB = pick([35, 40, 45]);

  // Stock and monitoring — built backwards from the food-cost % so that the whole
  // chain (Q21 consumed -> Q22 actual % -> Q24 points over target) stays exact and
  // the shop is always over target, never under.
  const dailyRev = pick([8000, 10000, 12000, 15000]);
  const weekSales = dailyRev * 7;
  const actualPct = round(targetA + pick([3, 4.5, 5, 6.5, 8, 10.5]), 1);
  const consumed = round((weekSales * actualPct) / 100, 0);
  const opening = Math.round((consumed * pick([0.3, 0.4, 0.5])) / 1000) * 1000;
  const closing = Math.round((consumed * pick([0.2, 0.25, 0.3])) / 1000) * 1000;
  const purchases = consumed - opening + closing;

  // percentages that come out clean
  const revenue = pick([300000, 400000, 500000, 600000]);
  const ebitdaPct = pick([15, 20, 25, 30, 33]);
  const rentPct = pick([8, 10, 12, 15]);

  return {
    milkRate, milkMl, milk,
    waterRate, waterMl, water,
    teaRate, teaG, tea,
    gingerRate, gingerG, ginger,
    sugarRate, sugarG, sugar,
    threeSum: round(milk + water + tea, 4),
    twoSum: round(ginger + sugar, 4),
    main, extras, total, wastePct, wasteAmt, foodCost,
    targetA, targetB,
    pctOfBase: pick([200, 300, 400, 500]),
    pctOf: pick([10, 15, 20, 25]),
    asDecimal: pick([20, 30, 40, 60, 75]),
    marginBase: pick([25, 30, 33, 35, 40]),
    butterPerKg: pick([400, 450, 500]),
    butterKg: pick([0.01, 0.015, 0.02]),
    onionPerKg: pick([30, 40, 50]),
    onionKg: pick([0.02, 0.025, 0.03]),
    opening, purchases, closing, consumed,
    dailyRev, weekSales, actualPct,
    revenue, ebitdaPct, rentPct,
    snackCost: pick([3, 4, 5, 6]),
    snackTarget: pick([20, 25, 40, 50])
  };
}

const FOOD_COST_RECIPES = {
  1: {
    text: s => `Milk costs ₹${s.milkRate} per ml. A recipe uses ${s.milkMl} ml. What's ${s.milkMl} × ${s.milkRate}?`,
    answer: s => s.milk,
    working: s => [`${s.milkMl} × ${s.milkRate}`, `= ${num(s.milk)}`]
  },
  2: {
    text: s => `Ginger costs ₹${s.gingerRate} per gram. A recipe uses ${s.gingerG} grams. What's ${s.gingerG} × ${s.gingerRate}?`,
    answer: s => s.ginger,
    working: s => [`${s.gingerG} × ${s.gingerRate}`, `= ${num(s.ginger)}`]
  },
  3: {
    text: s => `What is ${s.pctOf}% of ₹${num(s.pctOfBase)}?`,
    answer: s => (s.pctOfBase * s.pctOf) / 100,
    working: s => [`${num(s.pctOfBase)} × ${s.pctOf / 100}`, `= ${num((s.pctOfBase * s.pctOf) / 100)}`]
  },
  4: {
    text: s => `Write ${s.asDecimal}% as a decimal (e.g. 50% = 0.50).`,
    answer: s => s.asDecimal / 100,
    working: s => [`${s.asDecimal} ÷ 100`, `= ${num(s.asDecimal / 100)}`]
  },
  5: {
    text: s => `If your food cost is ${s.marginBase}% of your menu price, what's your gross margin? (100% − ${s.marginBase}%)`,
    answer: s => 100 - s.marginBase,
    working: s => [`100 − ${s.marginBase}`, `= ${100 - s.marginBase}`]
  },
  6: {
    text: s => `Water costs ₹${s.waterRate} per ml. A recipe uses ${s.waterMl} ml. What's the cost? (Round to 4 decimals)`,
    answer: s => s.water,
    working: s => [`${s.waterMl} × ${s.waterRate}`, `= ${num(s.water)}`]
  },
  7: {
    text: s => `Tea powder costs ₹${s.teaRate} per gram. A recipe uses ${s.teaG} grams. What's the cost?`,
    answer: s => s.tea,
    working: s => [`${s.teaG} × ${s.teaRate}`, `= ${num(s.tea)}`]
  },
  8: {
    text: s => `Sugar costs ₹${s.sugarRate} per gram. A recipe uses ${s.sugarG} grams. What's the cost?`,
    answer: s => s.sugar,
    working: s => [`${s.sugarG} × ${s.sugarRate}`, `= ${num(s.sugar)}`]
  },
  9: {
    text: s => `Butter costs ₹${s.butterPerKg} per kg. A recipe uses ${s.butterKg} of a kg (${s.butterKg * 1000}g). What's the cost?`,
    answer: s => round(s.butterPerKg * s.butterKg, 4),
    working: s => [`${s.butterPerKg} × ${s.butterKg}`, `= ${num(round(s.butterPerKg * s.butterKg, 4))}`]
  },
  10: {
    text: s => `Onion costs ₹${s.onionPerKg} per kg. One serving uses ${s.onionKg} of a kg (${s.onionKg * 1000}g). What's the cost?`,
    answer: s => round(s.onionPerKg * s.onionKg, 4),
    working: s => [`${s.onionPerKg} × ${s.onionKg}`, `= ${num(round(s.onionPerKg * s.onionKg, 4))}`]
  },
  11: {
    text: s => `Add these three ingredient costs: ₹${num(s.milk)} + ₹${num(s.water)} + ₹${num(s.tea)}. What's the total?`,
    answer: s => s.threeSum,
    working: s => [`${num(s.milk)} + ${num(s.water)} + ${num(s.tea)}`, `= ${num(s.threeSum)}`]
  },
  12: {
    text: s => `Add these two ingredient costs: ₹${num(s.ginger)} + ₹${num(s.sugar)}. What's the total?`,
    answer: s => s.twoSum,
    working: s => [`${num(s.ginger)} + ${num(s.sugar)}`, `= ${num(s.twoSum)}`]
  },
  13: {
    text: s => `Your main ingredients total ₹${num(s.main)} and your extra ingredients total ₹${num(s.extras)}. What's the combined total?`,
    answer: s => s.total,
    working: s => [`${num(s.main)} + ${num(s.extras)}`, `= ${num(s.total)}`]
  },
  14: {
    text: s => `Wastage is ${s.wastePct}% of ₹${num(s.total)}. What's the wastage amount? (Round to 2 decimals)`,
    answer: s => s.wasteAmt,
    working: s => [`${num(s.total)} × ${s.wastePct / 100}`, `= ${num(round((s.total * s.wastePct) / 100, 4))}, rounds to ${num(s.wasteAmt)}`]
  },
  15: {
    text: s => `Your ingredients total ₹${num(s.total)} and wastage adds ₹${num(s.wasteAmt)}. What's your total food cost?`,
    answer: s => s.foodCost,
    working: s => [`${num(s.total)} + ${num(s.wasteAmt)}`, `= ${num(s.foodCost)}`]
  },
  16: {
    text: s => `Your food cost is ₹${num(s.foodCost)}. Your target food-cost % is ${s.targetA}%. What should you charge? (Menu price = food cost ÷ target %)`,
    answer: s => round(s.foodCost / (s.targetA / 100), 2),
    working: s => [`${num(s.foodCost)} ÷ ${s.targetA / 100}`, `= ${num(round(s.foodCost / (s.targetA / 100), 2))} (round to ₹${Math.round(s.foodCost / (s.targetA / 100))})`]
  },
  17: {
    text: s => `Same food cost, ₹${num(s.foodCost)}, but this time your target is ${s.targetB}%. What should you charge?`,
    answer: s => round(s.foodCost / (s.targetB / 100), 2),
    working: s => [`${num(s.foodCost)} ÷ ${s.targetB / 100}`, `= ${num(round(s.foodCost / (s.targetB / 100), 2))} (round to ₹${Math.round(s.foodCost / (s.targetB / 100))})`]
  },
  18: {
    text: s => `If your food-cost target is ${s.targetA}%, what's your gross margin %?`,
    answer: s => 100 - s.targetA,
    working: s => [`100 − ${s.targetA}`, `= ${100 - s.targetA}`]
  },
  19: {
    text: s => `If your food-cost target is ${s.targetB}%, what's your gross margin %?`,
    answer: s => 100 - s.targetB,
    working: s => [`100 − ${s.targetB}`, `= ${100 - s.targetB}`]
  },
  20: {
    text: s => `A café made ${rs(s.revenue)} revenue and ${rs((s.revenue * s.ebitdaPct) / 100)} EBITDA. What % of revenue is that? (EBITDA ÷ revenue × 100)`,
    answer: s => s.ebitdaPct,
    working: s => [`${num((s.revenue * s.ebitdaPct) / 100)} ÷ ${num(s.revenue)}`, `= ${s.ebitdaPct / 100}, × 100 = ${s.ebitdaPct}%`]
  },
  21: {
    text: s => `Opening stock ${rs(s.opening)}. Purchases ${rs(s.purchases)}. Closing stock ${rs(s.closing)}. What's your food consumed? (Opening + Purchases − Closing)`,
    answer: s => s.consumed,
    working: s => [`${num(s.opening)} + ${num(s.purchases)} − ${num(s.closing)}`, `= ${num(s.consumed)}`]
  },
  22: {
    text: s => `Weekly sales are ${rs(s.weekSales)} and food consumed is ${rs(s.consumed)}. What's your food cost %? (Consumed ÷ sales × 100, round to 1 decimal)`,
    answer: s => s.actualPct,
    working: s => [`${num(s.consumed)} ÷ ${num(s.weekSales)}`, `= ${num(round(s.consumed / s.weekSales, 3))}, × 100 = ${num(s.actualPct)}%`]
  },
  23: {
    text: s => `Your daily revenue is ${rs(s.dailyRev)}. What's your revenue over 7 days?`,
    answer: s => s.weekSales,
    working: s => [`${num(s.dailyRev)} × 7`, `= ${num(s.weekSales)}`]
  },
  24: {
    text: s => `Your target food cost % is ${s.targetA}% but your actual is ${num(s.actualPct)}%. By how many percentage points are you over target?`,
    answer: s => round(s.actualPct - s.targetA, 1),
    working: s => [`${num(s.actualPct)} − ${s.targetA}`, `= ${num(round(s.actualPct - s.targetA, 1))}`]
  },
  25: {
    text: s => `A snack costs ₹${s.snackCost} to make in total. Your target food cost is ${s.snackTarget}%. What should you charge?`,
    answer: s => round(s.snackCost / (s.snackTarget / 100), 2),
    working: s => [`${s.snackCost} ÷ ${s.snackTarget / 100}`, `= ${num(round(s.snackCost / (s.snackTarget / 100), 2))}`]
  },
  26: {
    text: s => `Your rent is ${rs((s.revenue * s.rentPct) / 100)} and your monthly revenue is ${rs(s.revenue)}. What % of revenue does rent take up?`,
    answer: s => s.rentPct,
    working: s => [`${num((s.revenue * s.rentPct) / 100)} ÷ ${num(s.revenue)}`, `= ${s.rentPct / 100}, × 100 = ${s.rentPct}%`]
  }
};

/* ---------- registry ---------- */

const VARIANTS = {
  business: { scenario: businessScenario, recipes: BUSINESS_RECIPES },
  foodcost: { scenario: foodCostScenario, recipes: FOOD_COST_RECIPES }
};

/* Rebuild a question from its recipe. Returns the original untouched if the quiz
   has no recipe for it, so a partly-templated quiz still works. */
function shuffleQuestion(quizId, q, scenario) {
  const set = VARIANTS[quizId];
  const recipe = set && set.recipes[q.n];
  if (!recipe) return q;

  const val = (v) => (typeof v === "function" ? v(scenario) : v);
  const out = { ...q, text: val(recipe.text), answer: val(recipe.answer) };

  const working = val(recipe.working);
  if (Array.isArray(working)) { out.steps = working; delete out.working; }
  else { out.working = working; delete out.steps; }

  if (recipe.options) out.options = val(recipe.options);
  if (recipe.hint) out.hint = val(recipe.hint);
  if (recipe.formula) out.formula = val(recipe.formula);

  // a fixed accepted range belongs to the original numbers, so drop it
  delete out.min;
  delete out.max;
  if (recipe.tolerance != null) out.tolerance = recipe.tolerance;

  return out;
}

// how many of a quiz's questions can be shuffled
function shuffleCoverage(quizId, questions) {
  const set = VARIANTS[quizId];
  if (!set) return 0;
  return questions.filter(q => set.recipes[q.n]).length;
}
